### ISSUE TITLE
far vs. fas

### ISSUE THREAD

**Issue by 9Shuck** [JSotomayr/MyInstagramFeed#1]
Si en lugar de utilizar far en el icono del heart utilizaras fas te quedaría relleno. No entiendo el link a google ahí 😝

https://github.com/JSotomayr/MyInstagramFeed/blob/d595d31f217f4d9661babf886c85626963dd112d/index.html#L28

**Comment by JSotomayr** [comment]
Arreglado, corazón lleno, ya no hay vacío (que bonito 😢).

El enlace de google era una prueba que estaba haciendo y se me olvidó eliminarlo jajaja
